---
title: "my practice"
author: "Valeria Caras"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
#UNDERSTANDING WORLD POPULATION DYNAMICS (ex 1-3)
```{r cars}

#reading files
library(readr)
getwd()
setwd("/Users/valeriacaras/Downloads/R Studio")
Kenya <- read.csv("Kenia.csv",sep=";")
Sweden <- read.csv("Sweden.csv")
World <- read.csv("World.csv")

# computing crude birth rate (CBR) for Kenya. The crude birth rate is highest for Kenya,lowest for Sweden and on average for the world. For every  dataset the CBR decreased from the 1st period to the second meaning that fertility in general  has decreased everywhere
Kenya_1p <- Kenya[Kenya$period == '1950-1955',]
Kenya_1p_cbr <- sum(Kenya_1p$births )/sum(Kenya_1p$py.men + Kenya_1p$py.women)
Kenya_1p_cbr

Kenya_2p <- Kenya[Kenya$period == '2005-2010',]
Kenya_2p_cbr <- sum(Kenya_2p$births )/sum(Kenya_2p$py.men + Kenya_2p$py.women)
Kenya_2p_cbr
# compute crude birth rate (CBR) for Sweden
Sweden_1p <- Sweden[Sweden$period == '1950-1955',]
Sweden_1p_cbr <- sum(Sweden_1p$births )/sum(Sweden_1p$py.men + Sweden_1p$py.women)
Sweden_1p_cbr

Sweden_2p <- Sweden[Sweden$period == '2005-2010',]
Sweden_2p_cbr <- sum(Sweden_2p$births )/sum(Sweden_2p$py.men + Sweden_2p$py.women)
Sweden_2p_cbr
# compute crude birth rate (CBR) for World
World_1p <- World[World$period == '1950-1955',]
World_1p_cbr <- sum(World_1p$births )/sum(World_1p$py.men + World_1p$py.women)
World_1p_cbr

World_2p <- World[World$period == '2005-2010',]
World_2p_cbr <- sum(World_2p$births )/sum(World_2p$py.men + World_2p$py.women)
World_2p_cbr

# compute age-specific fertility rate (ASFR) for Kenya
# The tendancy : women in Kenya give birth earlier than in Sweden and in the World
Kenya_1p <- Kenya[c(4:10),]
Kenya_1p_asfr <- Kenya_1p$births/Kenya_1p$py.women
Kenya_1p_asfr 

Kenya_2p <- Kenya[c(19:25),]
Kenya_2p_asfr <- Kenya_2p$births/Kenya_2p$py.women
Kenya_2p_asfr 

# compute age-specific fertility rate (ASFR) for Sweden
Sweden_1p <- Sweden[c(4:10),]
Sweden_1p_asfr <- Sweden_1p$births/Sweden_1p$py.women
Sweden_1p_asfr 

Sweden_2p <- Sweden[c(19:25),]
Sweden_2p_asfr <- Sweden_2p$births/Sweden_2p$py.women
Sweden_2p_asfr

# compute age-specific fertility rate (ASFR) for World
World_1p <- World[c(4:10),]
World_1p_asfr <- World_1p$births/World_1p$py.women
World_1p_asfr 

World_2p <- World[c(19:25),]
World_2p_asfr <- World_2p$births/World_2p$py.women
World_2p_asfr

# calculate the total fertility rate (TFR) for Kenya
# The average number of children that women give birth to if they live through their entire reproductive age is highest in Kenya, but it decreased from 7.59 (1950-1955) to 4.87 (2005 -2010). the lowest TFR is again in Sweden - women tend to born on average 2.22 children in 50s but in 2010s the number decreased to 1.9. The decreasing over time tendency is also common for the world (from 5 to 2.54).
Kenya_1p_trf <- Kenya_1p_asfr[1]*5 + Kenya_1p_asfr[2]*5 +Kenya_1p_asfr[3]*5 +Kenya_1p_asfr[4]*5 +Kenya_1p_asfr[5]*5 +Kenya_1p_asfr[6]*5 +Kenya_1p_asfr[7]*5 
Kenya_1p_trf 

Kenya_2p_trf <- Kenya_2p_asfr[1]*5 + Kenya_2p_asfr[2]*5 +Kenya_2p_asfr[3]*5 +Kenya_2p_asfr[4]*5 +Kenya_2p_asfr[5]*5 +Kenya_2p_asfr[6]*5 +Kenya_2p_asfr[7]*5 
Kenya_2p_trf 
# calculate the total fertility rate (TFR) for Sweden
Sweden_1p_trf <- Sweden_1p_asfr[1]*5 + Sweden_1p_asfr[2]*5 +Sweden_1p_asfr[3]*5 +Sweden_1p_asfr[4]*5 + Sweden_1p_asfr[5]*5 +Sweden_1p_asfr[6]*5 + Sweden_1p_asfr[7]*5 
Sweden_1p_trf 

Sweden_2p_trf <- Sweden_2p_asfr[1]*5 + Sweden_2p_asfr[2]*5 +Sweden_2p_asfr[3]*5 +Sweden_2p_asfr[4]*5 +Sweden_2p_asfr[5]*5 +Sweden_2p_asfr[6]*5 +Sweden_2p_asfr[7]*5 
Sweden_2p_trf
# calculate the total fertility rate (TFR) for World
World_1p_trf <- World_1p_asfr[1]*5 + World_1p_asfr[2]*5 +World_1p_asfr[3]*5 +World_1p_asfr[4]*5 +World_1p_asfr[5]*5 +World_1p_asfr[6]*5 +World_1p_asfr[7]*5 
World_1p_trf 

World_2p_trf <- World_2p_asfr[1]*5 + World_2p_asfr[2]*5 +World_2p_asfr[3]*5 +World_2p_asfr[4]*5 +World_2p_asfr[5]*5 +World_2p_asfr[6]*5 +World_2p_asfr[7]*5 
World_2p_trf
```

#UNDERSTANDING WORLD POPULATION DYNAMICS (ex 4-6)

```{r pressure, echo=FALSE}
#crude death rate (CDR) for Kenya
#The highest death reate is observed in Kenya, but it has decreased in the 2nd period. The lowest death rate in Swedem (also decresed in the 2nd period). Average death rate for the world has decreased most considerably 
Kenya_1p_crbr <- sum(Kenya_1p$deaths)/sum(Kenya_1p$py.men + Kenya_1p$py.women)
Kenya_1p_crbr

Kenya_2p_crbr <- sum(Kenya_2p$deaths)/sum(Kenya_2p$py.men + Kenya_2p$py.women)
Kenya_2p_crbr
#crude death rate (CDR) for Sweden
Sweden_1p_crbr <- sum(Sweden_1p$deaths)/sum(Sweden_1p$py.men + Sweden_1p$py.women)
Sweden_1p_crbr

Sweden_2p_crbr <- sum(Sweden_2p$deaths)/sum(Sweden_2p$py.men + Sweden_2p$py.women)
Sweden_2p_crbr
#crude death rate (CDR) for World
World_1p_crbr <- sum(World_1p$deaths)/sum(World_1p$py.men + World_1p$py.women)
World_1p_crbr

World_2p_crbr <- sum(World_2p$deaths)/sum(World_2p$py.men + World_2p$py.women)
World_2p_crbr

#age-specific death rate (ASDR) for Kenya 2005-2010 by age
#taking into account the age composition os population the indicator has considerably lower values in Sweden, especially for elderly while in Kenya people die from the middle age to elderly + new-borns deaths quite significant
Kenya_2p <- Kenya[c(16:30),]
Kenya_2p_asdr <- Kenya_2p$deaths/(Kenya_2p$py.men + Kenya_2p$py.women)
Kenya_2p_asdr

#age-specific death rate (ASDR) for Sweden 2005-2010 by age
Sweden_2p <- Sweden[c(16:30),]
Sweden_2p_asdr <- Sweden_2p$deaths/(Sweden_2p$py.men + Sweden_2p$py.women)
Sweden_2p_asdr

#computing alternative CDR for Kenya (based on Sweden's population) for period 2005-2010
#Indicator taking into the account the age distribution shows that death rate becomes significanly higher for kenya (2005-2015) compared to the distribution of Sweden's population
Sweden_2p <- Sweden[c(16:30),]
Sweden_proportions <- (Sweden_2p$py.men + Sweden_2p$py.women)/sum(Sweden_2p$py.men + Sweden_2p$py.women)
Sweden_proportions

Kenya_2p <- Kenya[c(16:30),]
CDR_last <- sum(Kenya_2p_asdr*Sweden_proportions)
CDR_last
```
```{r}
#Own dataset. Cases - Eastern Partneship countries, number of observations (84 country-year), 14 variables
library(readxl)
library(ggplot2)
my_data <- read_excel("data_time series.xlsx")
str(my_data)
head(my_data)
summary(my_data)
#ploting the variables of interest  - distributions of gdp and resources are not mormal -> later will use log() trabsormation plotting regression
gdp_distribution <- ggplot(my_data, aes(gdp)) + geom_histogram()
gdp_distribution

resources_distribution <- ggplot(my_data, aes(resources)) + geom_histogram()
resources_distribution

#linear model predicting gdp by resources. Model predicts 6,7% of observations (Adjusted R-squared) considering the fact that only Azerbaijan in the dataset can be regarded as country with resources. Revenues from the resources contribute to the increase of gdp at significant level of 0.01. F-statistic is significant that means model provides a better fit than the intercept-only model
model <- lm(gdp ~ resources, my_data)
summary(model)

#plot results

ggplot(my_data, aes(gdp,resources)) + geom_point() + geom_smooth(method = "lm") +  labs(x = "GDP per capita (thousands $)",
       y = "Resources") + scale_x_log10() + scale_y_log10()
#diagnosis

#leverage cases : 16,17,18,19, 22 - all for Azerbaijan 
library(dplyr)
library(broom)
leverage <- model %>%
  augment() %>%
  arrange(desc(.hat)) %>%
  head(n=5)
leverage
#influential observations: 15,16,17 - Azerbaijan; 57,58 - Moldova; leverage and influential  observations overlap  only for 2 cases (Azerbaijan 16,17), so only two cases with high leverage are influential observations 
influential_obs<- model %>%
  augment() %>%
  arrange(desc(.cooksd)) %>%
  head(n=5)
influential_obs 
#outliners, case 15 (Azerbaijan) is an outliner
library(broom)
library(car)
qqPlot(model,labels=row.names(my_data), id.method="identify",
         simulate=TRUE, main="Q-Q Plot")
outlierTest(model)

```


