---
title: "Thesis data2_trust2"
author: "Valeria Caras"
date: "11/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(sjPlot)
library(lme4)
library(survey)
library(readxl)
```

```{r}
setwd("/Users/valeriacaras/Downloads/R Studio")
round_2<- read_excel("round_2_lwc_20102020.xlsx")

#compute variables as in round 1
round_2 <- round_2 %>% mutate(urban = case_when(urbanisation %in% 1:2 ~ 0, urbanisation %in% 3:4 ~ 1))
round_2 <- round_2 %>% mutate(hous_ends = case_when(makeends %in% 1:3 ~ 0, makeends %in% 4:6 ~ 1))
round_2 <- round_2%>% mutate(ind_health = case_when(general_health %in% 1:3 ~ 0, general_health %in% 4:5 ~ 1))
round_2<- round_2 %>% mutate(gend = case_when(gender == 1 ~ "M", gender == 2 ~ "F"))

round_2_selected <- round_2[, c("w_gross_trim", "CASE", "country", "gend", "age_group", "ind_health", "trust_govern", "trust_healthcare", "urban", "emp_stat", "lostjob_2", "job_insec", "hous_ends", "finance_last3m", "finance_next3m", "edu_level", "trust_media",  "democ_satisf","empstst_beforecd","info_covid","received_sup","supp_ifhelpful","wagesupp","benefits_ifhelp","age")]


```

```{r}
##ADD COUNTRY LEVEL VARIABLES
#add clarity index (enp+polar + seats in gover + single party gov/4)
 round_2_selected <- round_2_selected  %>% mutate(clarity_index = case_when(
   country == 1 ~ 0.39,
   country == 2 ~ 0.46,
   country == 3 ~ 0.36,
   country == 4 ~ 0.36,
   country == 5 ~ 0.46,
   country == 6 ~ 0.49,
   country == 7 ~ 0.74,
   country == 8 ~ 0.28,
   country == 9 ~ 0.34,
   country == 10 ~ 0.47,
   country == 11 ~ 0.37,
   country == 12 ~ 0.67,
   country == 13 ~ 0.33,
   country == 14 ~ 0.35,
   country == 15 ~ 0.41,
   country == 16 ~ 0.38,
   country == 17 ~ 0.37,
   country == 18 ~ 0.32,
   country == 19 ~ 0.55,
   country == 20 ~ 0.44,
   country == 21 ~ 0.32,
   country == 22 ~ 0.38,
   country == 23 ~ 0.64,
   country == 24 ~ 0.38,
   country == 25 ~ 0.4,
   country == 26 ~ 0.36,
   country == 27 ~ 0.41
 ))
#calculated for round 2
round_2_selected <- round_2_selected  %>% mutate(govresponse_oxf = case_when(
   country == 1 ~ 56.85,
   country == 2 ~ 58.61,
   country == 3 ~ 45.98,
   country == 4 ~ 47.80,
   country == 5 ~ 63.96,
   country == 6 ~ 46.79,
   country == 7 ~ 63.64,
   country == 8 ~ 32.41,
   country == 9 ~ 41.34,
   country == 10 ~ 58.43,
   country == 11 ~ 61.76,
   country == 12 ~ 58.96,
   country == 13 ~ 58.63,
   country == 14 ~ 54.50,
   country == 15 ~ 65.34,
   country == 16 ~ 54.91,
   country == 17 ~ 43.26,
   country == 18 ~ 48.01,
   country == 20 ~ 53.13,
   country == 21 ~ 49.80,
   country == 22 ~ 68.95,
   country == 23 ~ 47.90,
   country == 24 ~ 53.00,
   country == 25 ~ 50.06,
   country == 26 ~ 60.39,
   country == 27 ~ 55.36,
   country == 29 ~ 71.93
    
 ))

round_2_selected <- round_2_selected  %>% mutate(name_country = case_when(
   country == 1 ~ "AT",
   country == 2 ~ "BE",
   country == 3 ~ "BU",
   country == 4 ~ "CR",
   country == 5 ~ "CY",
   country == 6 ~ "CZ",
   country == 7 ~ "DN",
   country == 8 ~ "ES",
   country == 9 ~ "FI",
   country == 10 ~ "FR",
   country == 11 ~ "GER", 
   country == 12 ~ "GR",
   country == 13 ~ "HU",
   country == 14 ~ "IR",
   country == 15 ~ "IT",
   country == 16 ~ "LAT",
   country == 17 ~ "LITH",
   country == 18 ~ "LU",
   country == 19 ~ "MA",
   country == 20 ~ "NETH",
   country == 21 ~ "POL",
   country == 22 ~ "POR",
   country == 23 ~ "ROM",
   country == 24 ~ "SLV",
   country == 25 ~ "SLN",
   country == 26 ~ "SP",
   country == 27 ~ "SW",
   country == 29 ~ "UK"
    
 ))

write.csv(round_2_selected, "round_2_selected.csv")
```

```{r}
#exporing data, creating design
 
 #arrange countried by trust
 comparison_trust_gover2 <- round_2_selected %>% group_by(name_country) %>% summarise(avg_trust = mean(trust_govern, na.rm = TRUE))%>%
    arrange(avg_trust)
 comparison_trust_gover2
 
 #create design (cases within countries)
library(survey)
  round_2_selected <- round_2_selected %>% group_by(country) %>% mutate( n = n())
 design_2 <- svydesign(data = round_2_selected, weights = ~ w_gross_trim, strata = ~ country, fpc = ~n, id = ~CASE)
summary(design_2)

#Dependent variable 
svymean(~trust_govern, design_2,  na.rm = TRUE) #lower compared to April. In April mean  - 4.77, now 4.63
table2 <- svytable(~trust_govern, design_2) %>% as.data.frame()
table2

summary(round_2_selected$emp_stat)


```

```{r}
#lost  job2, job_insec to many NaNs, emp_stst better

#converting variables as factors (esp emp_stat)
round_2_selected$age_group <- relevel(factor(round_2_selected$age_group), ref = "1")
round_2_selected$gend <- relevel(factor(round_2_selected$gend), ref ="M")
round_2_selected$emp_stat <- relevel(factor(round_2_selected$emp_stat), ref="1")
round_2_selected$ind_health <- relevel(factor(round_2_selected$ind_health), ref = "0")
round_2_selected$lostjob_2  <- relevel(factor(round_2_selected$lostjob_2), ref="0")
round_2_selected$job_insec <- relevel(factor(round_2_selected$job_insec), ref = "0")
round_2_selected$finance_last3m <- relevel(factor(round_2_selected$finance_last3m), ref="2")
round_2_selected$finance_next3m <- relevel(factor(round_2_selected$finance_next3m), ref="2")
round_2_selected$hous_ends <- relevel(factor(round_2_selected$hous_ends), ref="1")
round_2_selected$edu_level <- relevel(factor(round_2_selected$edu_level), ref="1")
round_2_selected$urban<- relevel(factor(round_2_selected$urban),ref="0")
round_2_selected$received_sup <- relevel(factor(round_2_selected$received_sup), ref = "4")
round_2_selected$wagesupp <- relevel(factor(round_2_selected$wagesupp), ref = "4")

round2_clean <- round_2_selected[, c("w_gross_trim", "CASE", "name_country", "gend", "age_group", "ind_health", "trust_govern", "trust_EU", "trust_heathcare", "urban", "emp_stat", "lostjob_2", "job_insec", "hous_ends", "finance_last3m", "finance_next3m", "edu_level", "trust_media", "democ_satisf","received_sup","wagesupp","clarity_index","govresponse_oxf","age")]

round2_clean <- na.omit(round2_clean)

table(round2_clean$received_sup)
table(round2_clean$wagesupp)
```

```{r}
#Modeling
#interaction  clarity_index*job_insec/lostjob_2 is not significant anymore, but interaction clarity_index*received_sup[2 - requested but not received] is significant and inter = 7.30; the same with wagesupp; inter between clarity index and trust in healtcare is not sign
#puting econ perceptions in random part does not improve the model and ICC the same
#probably better without lostjob (few oobs)
m2_interact2 <- lmer(trust_govern ~trust_heathcare + age_group + gend + edu_level + ind_health + urban + job_insec +  finance_next3m + finance_last3m + clarity_index + govresponse_oxf + clarity_index*received_sup  + received_sup+ (1 +  trust_heathcare|name_country), data=round2_clean,  weights = w_gross_trim, na.action = na.omit, REML = F)

tab_model(m2_interact2)
summary(m2_interact2)
ranef(m2_interact2)
plot_model(m2_interact2)
plot_model(m2_interact2, type = "re")
#same model but trust in healtcare only in randm part
m2_interact3 <- lmer(trust_govern ~age_group + gend + edu_level + ind_health + urban + job_insec + lostjob_2 +  finance_next3m + finance_last3m + clarity_index + govresponse_oxf + clarity_index*received_sup  + received_sup+ (1 +  trust_heathcare|name_country), data=round2_clean,  weights = w_gross_trim, na.action = na.omit, REML = F)

tab_model(m2_interact3)
summary(m2_interact3)

anova(m2_interact2,m2_interact3) #m2_interact2 statistically better 

#random inter model
m_cnts_econ_clarity2 <- lmer(trust_govern ~ trust_heathcare + age_group + gend + edu_level + ind_health + urban + job_insec + lostjob_2 + finance_next3m + finance_last3m + clarity_index+ govresponse_oxf + received_sup +
                            (1|name_country), data=round2_clean,  weights = w_gross_trim, na.action = na.omit, REML = F)
tab_model(m_cnts_econ_clarity2)

anova(m_cnts_econ_clarity2, m2_interact2) #m2_interact2 statistically better, the best model for now

tab_model(m2_interact2, m2_interact3, m_cnts_econ_clarity2)

```

```{r}
summary(round2_clean$edu_level)
#Centering
#age cent does not bring linearity
round2_clean <- round2_clean %>% 
  # Grand mean centering (CMC)
  mutate(cent.healtcare = trust_heathcare-mean(trust_heathcare)) 

round2_clean <- round2_clean %>% 
  mutate(cent.educ = as.numeric(edu_level)-mean(as.numeric(edu_level)))

round2_clean <- round2_clean %>% 
  mutate(cent.age = age-mean(age))
#centering level 2 around population mean ?

round2_clean$cent.response <- round2_clean$govresponse_oxf-mean(round2_clean$govresponse_oxf)

round2_clean$cent.clarity <- round2_clean$clarity_index - mean(round2_clean$clarity_index)

#moodel with centering
m2_int2_cent <- lmer(trust_govern ~cent.healtcare + age_group+ gend + cent.educ + ind_health + urban + job_insec +  finance_next3m + finance_last3m + cent.clarity  + cent.response+ cent.clarity *received_sup  + received_sup+ (1 +  cent.healtcare|name_country), data=round2_clean,  weights = w_gross_trim, na.action = na.omit, REML = F)

tab_model(m2_int2_cent)

```



```{r}
#Model diagnstics
#Check for linearity
linearity2<-plot(resid(m2_interact2),round2_clean$trust_govern) 
linearity2
#Check for normality
library(lattice)
qqmath(m2_interact2)

plot(m2_int2_cent)
plot_model(m2_interact2, type="diag") #complex model diag

#diag centered
plot_model(m2_int2_cent, type="diag")

##assumption of homogenity is violated
round2_clean$res <- abs(residuals(m2_int2_cent))^2 
levene_model <- lm(res ~ CASE, data=round2_clean) 
anova(levene_model)

#test for multicolinearity
vif.mer <- function (fit) {
 
  v <- vcov(fit)
  nam <- names(fixef(fit))
  
  ns <- sum(1 * (nam == "Intercept" | nam == "(Intercept)"))
  if (ns > 0) {
    v <- v[-(1:ns), -(1:ns), drop = FALSE]
    nam <- nam[-(1:ns)]
  }
  
  d <- diag(v)^0.5
  v <- diag(solve(v/(d %o% d)))
  names(v) <- nam
  v
}

vif.mer(m2_interact2)

vif.mer(m2_int2_cent) #centering resolves multi-collinearity
#qq plot
qqnorm(residuals(m2_interact2), family="serif")
qqline(residuals(m2_interact2)) #normal one

#Marginal effects for mixed moodels

pr2 <- ggpredict(m2_interact2, "trust_heathcare")
plot(pr2)

pr3 <- ggpredict(m2_interact2, c("job_insec", "finance_next3m"))
plot(pr3)

pr_rand2 <- ggpredict(m_interact2, "finance_last3m", type = "random")
plot(pr_rand2)
#by countries
me2 <- ggpredict(m_interact2, terms = c("job_insec", "name_country[sample=7]"), type = "random")
plot(me2)
```

